name: pycomfort
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - twine
  - more-itertools
  - setuptools
  - click
  - pip:
      - pyfunctional
      - loguru
      - python-dotenv
      - Deprecated